Repository wibsonorg/notary-sdk, pull requests merged in 2019-04, with the labels that each got.

#76 Swagger input validation
  notary-api/package-lock.json
  notary-api/package.json
  notary-api/src/app.js
  notary-api/src/routes/buyers.js
  notary-api/src/routes/dataResponses.js
  notary-api/src/routes/sellers.js
  notary-api/src/utils/routes.js
  notary-api/src/utils/wibson-lib/package.json
Labels: enhancement

#80 fix payment/unlock test
  notary-api/src/jobs/payments.js
Labels: bug

#79 Fixes validate data in SendUnlock
  notary-api/.env.example
  notary-api/config/index.js
  notary-api/src/blockchain/batPay.js
  notary-api/src/blockchain/contractEventSubscribers.js
  notary-api/src/blockchain/dataOrder.js
  notary-api/src/jobs/payments.js
  notary-api/src/utils/jobify.js
  notary-api/test/jobs/payments.mock.js
Labels: wip

#81 Fix Unlock
  notary-api/config/index.js
  notary-api/src/blockchain/contractEventSubscribers.js
  notary-api/src/operations/notarize.js
  notary-api/src/utils/web3.js
  notary-api/test/operations/notarize.mock.js
  notary-api/test/operations/snapshots/notarize.test.js.md
  notary-api/test/operations/snapshots/notarize.test.js.snap
Labels: bug
